version: '3'
services:
  database:
    image: postgres
    environment:
      - POSTGRE_USER=value
      - POSTGRE_DATABASE=test
      - POSTGRES_PASSWORD=test
    ports:
      - "8080"
    container_name: tcc_docker_services

  activemq:
    image: vromero/activemq-artemis:latest-alpine
    container_name: activemq
    environment:
      ARTEMIS_USERNAME: user-amq
      ARTEMIS_PASSWORD: password-amq
    ports:
      - "8161:8161"
      - "61616:61616"