version: '3'
services:
  database:
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: developer
        POSTGRES_PASSWORD: developer
    ports:
      - "8180:5432"
    container_name: tcc_docker_services
